site_name: ELISE DOBBE

nav:
  - Home: index.md
  - Projects: projects.md
  - About: about.md
  - CV: cv.md

theme:
  name: material
  favicon: assets/images/favicon.png
  palette:
    - scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  custom_dir: docs/overrides

plugins: []

extra_css:
  - assets/styles/extra.css
