site_name: ELISE DOBBE

nav:
  - Home: index.md
  - Projects: projects.md
  - About: about.md
  - CV: cv.md

theme:
  name: material
  # Mørk side, ingen toggle, ingen søkefelt
  palette:
    - scheme: slate
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

# Dette fjerner søk (MkDocs sin built-in search)
plugins: []

extra_css:
  - assets/styles/extra.css
