site_name: ELISE DOBBE

nav:
  - Home: index.md
  - Projects: projects.md
  - About me: about.md
  - CV: cv.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top

extra_css:
  - assets/styles/extra.css
