site_name: ELISE DOBBE

nav:
  - ELISE DOBBE: index.md
  - Projects: projects.md
  - About me: about.md

theme:
  name: material
  favicon: assets/images/favicon.png
  palette:
    - scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  custom_dir: docs/overrides

plugins: []

extra_css:
  - assets/styles/extra.css

extra_javascript:
  - assets/javascripts/extra.js
